services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DB_NAME} -U $${DB_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_network
    user: postgres

  adminer:
    image: adminer:4-standalone
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - chat_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data:
    driver: local

networks:
  chat_network:
    driver: bridge